services:
  neo4j:
    image: neo4j:5.20
    container_name: rcg-neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/rcgdevpassword
      NEO4J_PLUGINS: '["apoc"]'
    volumes:
      - rcg-neo4j-data:/data

volumes:
  rcg-neo4j-data:
